/**
 * @license NgRx 9.1.2+7.sha-914de92
 * (c) 2015-2018 Brandon Roberts, Mike Ryan, Rob Wormald, Victor Savkin
 * License: MIT
 */
function sum(a, b) {
    return a + b;
}

/**
 * DO NOT EDIT
 *
 * This file is automatically generated at build
 */

export { sum };
//# sourceMappingURL=component-store.js.map
